language: php
php:
  - 5.3
  - 5.4
services:
  - mongodb
before_script:
  # Composer
  - composer install
  # Mongo
  - pecl -q install mongo-1.2.10 && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
script: cd ./tests && phpunit